### ISSUE TITLE
Add feature to indicate session state on tray icon

### ISSUE THREAD

**Issue by bizzbyster** [Project-Faster/qpep#2]
Currently when running the tray icon on Windows, there is no indication that qpep client is "connected" to a qpep server. In addition, it is not possible to know that data is going through qpep. Perhaps we could add a connected indicator and also some kind of activity notification -- maybe a simple activity indicator.

**Comment by parvit** [comment]
Hi, 
I was thinking about handling the visual part with an updating icon, right now the tray icon is fixed and with the modificaion you would have a three-state indicator:
1) Current icon: _Not Connected_
2) Blinking Yellow icon: _Connecting / Temporary disconnection_
3) Green fixed icon: _Connected_

The underlying changes would be of:
* *Server*: A new http api server (on a dedicated port), which at this time would only expose an GET endpoint of "status"
* *Client and Tray*: A periodic (~1sec) http request to the status api of the gateway (diverted in the same way as the other local connections)
* *Configuration file*: A new parameter to specify the remote api request port

The actual status of the icon would be based on the tray's request result, so right now the client request would be redundant, however i'm inclined to have it so that in the future new features/apis can be added with less effort.

Some of those might include things like dynamic configuration or statistics collection from the server or it also could be a way to let other systems know about the current state of the connection.

Let me know what you think,
Vittorio.

**Comment by bizzbyster** [comment]
I like it. @mfoxworthy can you comment please?

**Comment by mfoxworthy** [comment]
When we say connected, what does that actually mean?. The proxy itself just proxies connections, but there is no state. Is the connection status just based on the http port? How well will this method scale when there are thousands of clients on a server? Have you thought about how this would work behind a load balancer?

**Comment by parvit** [comment]
Hi, @mfoxworthy from my initial proposal i've actually expanded a bit what was needed in terms of api.

Two are actually needed:
1) */api/v1/echo* which returns a json with the _public_ address / port of the client
2) */api/v1/status/:addr* which consumes the address parameter to return a count of the active connections that the server is handling for that client

So basically if you have both the correct echo _and_ at least a running connection than it is counted as _connected_, instead you would keep the _connecting_ status.

This handles in a clean way both failed connections to the server and temporary loss of connection.
I suppose it also cover the case for load balancers, because if at least one of the responding servers answers the connection than the path is open.

**Comment by mfoxworthy** [comment]
@parvit Most excellent. Peter and I just spoke about this, and I was going to update the issue. But part 2 in your last message addresses the topic perfectly. I think we need to think through the load balancer a bit more, but I think this initial version should cover most of the features.

**Comment by bizzbyster** [comment]
I like the idea of a state variable in the UI -- 

Current icon: Not Connected / Disabled
Blinking Yellow icon: Connecting / Temporary disconnection
Green fixed icon: Connected

And then also a metric that indicates activity in some way -- bytes transferred over the tunnel, etc.

**Comment by bizzbyster** [comment]
@parvit @mfoxworthy thoughts? I'd like to get this feature design nailed down today if possible.

**Comment by parvit** [comment]
@bizzbyster The collection of statistics as you say would be a considerably higher effort, and it would not be a week effort anymore but something more.

How much more depends on the exact list of statistics you would require to have and the dedicated gui it would require to have, because i think everything would not fit into the tray icon.

If instead we want to keep this as a next feature to develop i will soon have the change ready to test.

**Comment by bizzbyster** [comment]
Sounds good -- let's add that as an additional feature. @mfoxworthy agreed?

**Comment by parvit** [comment]
Hi @bizzbyster @mfoxworthy, the PR for this feature is ready please test it and send me feedback.

**Comment by bizzbyster** [comment]
Awesome I will!

**Comment by mfoxworthy** [comment]
> Hi @bizzbyster @mfoxworthy, the PR for this feature is ready please test it and send me feedback.

Wow! That was fast! Thanks!

**Comment by parvit** [comment]
Hi, was there progress on testing this ?

**Comment by bizzbyster** [comment]
@parvit I'll be totally honest -- my Windows license seems to have expired and I'm waiting on my IT to help me resolve it. Very annoying! Will provide feedback as soon as I'm able.

**Comment by parvit** [comment]
well ain't that a bummer.
hope you get it sorted out soon.

Il Mar 19 Lug 2022, 20:01 bizzbyster ***@***.***> ha scritto:

**Comment by parvit** [comment]
@mfoxworthy what about you? were you able to test?

**Comment by bizzbyster** [comment]
I'm sorted out and will test this weekend.

**Comment by bizzbyster** [comment]
We have a few more running over satellite who want to test but I would like to get some basic sense of it working before I offer it.

**Comment by bizzbyster** [comment]
@parvit I'm testing the new tray icon indicating session state and it seems stuck in waiting...

![image](https://user-images.githubusercontent.com/4001792/180487691-96ca9935-1091-4107-84f6-2c8f3bc62bdb.png)

Despite the fact that the server is up and running. I will email you the server IP so maybe you can see if it works for you?

**Comment by parvit** [comment]
Its really late here so i won't be able to test it right now, tomorrow morning i'll try.

To get one thing out of the way: did you build and use all the three updated binaries together? 
Meaning the qpep client/server and the tray (obviously the tray you're ok as the icon is the right one).

If so than the client/server should be producing a qpep.log file in the running directory, can you post it? thanks.

**Comment by bizzbyster** [comment]
I will look for the log file on my test machine.

**Comment by parvit** [comment]
Seems that by email the test was completed successfully, however i can't close / merge the change as i don't have write access for this repo.

**Comment by parvit** [comment]
Closing the issue, i'll open a bug for the testing of the api server.
